import katalon from "@katalon-studio/cloud-test";

export default katalon.testCase("New Test Case", async ({ local, web }) => {
  await new Promise((r) => setTimeout(r, 0));
  await web.openBrowser("https://katalon-demo-cura.herokuapp.com");
  await web.click({
    type: "Web",
    id: "7b9120a2-404c-4fde-af40-8571763a6376",
    attributes: {
      id: "menu-toggle",
      href: "#",
      class: "btn btn-dark btn-lg toggle",
    },
    childIndex: 2,
    hashes: { "md5.v1": "bd1a4d233fee02bdbcf85af89867c9de" },
    name: "a - btn btn-dark btn-lg toggle",
    selectors: [
      {
        id: "d5d9f0aa-5cc5-467d-806d-2189af1cdab4",
        type: "CSS",
        value: "#menu-toggle",
        isDefault: true,
      },
      {
        id: "74bdf81a-ab22-4dba-9d83-dd80db7e04c9",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "a",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "e119faf5-8e2b-4cb6-88da-5079bd9a76a4",
    attributes: { href: "./", onclick: "$('#menu-close').click();" },
    childIndex: 1,
    hashes: { "md5.v1": "55fbd90a737c1163415dd358745da1b2" },
    name: "a - Home",
    selectors: [
      {
        id: "2d798a01-889d-4192-a9c4-f77b2b705d23",
        type: "CSS",
        value: 'li:nth-child(3) [href="\\.\\/"]',
        isDefault: true,
      },
      {
        id: "769129bf-93e6-4ebe-8736-001bac9e0197",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "a",
    text: "Home",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "4ad8b8b2-fcb6-4ca6-a132-699bf18ff343",
    attributes: {
      id: "menu-toggle",
      href: "#",
      class: "btn btn-dark btn-lg toggle",
    },
    childIndex: 2,
    hashes: { "md5.v1": "bd1a4d233fee02bdbcf85af89867c9de" },
    name: "a - btn btn-dark btn-lg toggle",
    selectors: [
      {
        id: "805237c2-d54c-4e1e-b1ae-a8f9c41d5761",
        type: "CSS",
        value: "#menu-toggle",
        isDefault: true,
      },
      {
        id: "c83e765e-070c-49fb-ab8a-1c2c7e6ab333",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "a",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "b35af805-8695-4f85-a9ae-79b28fd5b908",
    attributes: {
      href: "profile.php#login",
      onclick: "$('#menu-close').click();",
    },
    childIndex: 1,
    hashes: { "md5.v1": "0bd0cc05e00accd5b4b22670791231d9" },
    name: "a - Login",
    selectors: [
      {
        id: "ba0c2a82-1238-46ce-b965-de6decc65324",
        type: "CSS",
        value: '[href="profile\\.php\\#login"]',
        isDefault: true,
      },
      {
        id: "8b3f2432-9d65-4d5d-8ac1-5f2993a2f98f",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "a",
    text: "Login",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.doubleClick({
    type: "Web",
    id: "47285e1c-8823-44c5-a407-d134d076067a",
    attributes: {
      type: "text",
      class: "form-control",
      placeholder: "Username",
      "aria-describedby": "demo_username_label",
      value: "John Doe",
      readonly: "",
    },
    childIndex: 2,
    hashes: { "md5.v1": "d658d4e8da92fe56536b7b268fa72a89" },
    name: "input - Username",
    selectors: [
      {
        id: "8ffe1f2c-2024-40de-a857-dd049daa8d9c",
        type: "CSS",
        value: '[value="John\\ Doe"]',
        isDefault: true,
      },
      {
        id: "8032c446-2312-4c76-af81-8db8e4f7c7ac",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "input",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "47285e1c-8823-44c5-a407-d134d076067a",
    attributes: {
      type: "text",
      class: "form-control",
      placeholder: "Username",
      "aria-describedby": "demo_username_label",
      value: "John Doe",
      readonly: "",
    },
    childIndex: 2,
    hashes: { "md5.v1": "d658d4e8da92fe56536b7b268fa72a89" },
    name: "input - Username",
    selectors: [
      {
        id: "8ffe1f2c-2024-40de-a857-dd049daa8d9c",
        type: "CSS",
        value: '[value="John\\ Doe"]',
        isDefault: true,
      },
      {
        id: "8032c446-2312-4c76-af81-8db8e4f7c7ac",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "input",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "294ca06e-1700-48a3-9211-7c5c8b669e67",
    attributes: {
      type: "text",
      class: "form-control",
      id: "txt-username",
      name: "username",
      placeholder: "Username",
      value: "",
      autocomplete: "off",
    },
    childIndex: 1,
    hashes: { "md5.v1": "57f176ba19cb19cc93acaba2dbde6b10" },
    name: "input - Username",
    selectors: [
      {
        id: "bfdad4d5-fe3b-4012-93d8-096c44aeab07",
        type: "CSS",
        value: "#txt-username",
        isDefault: true,
      },
      {
        id: "d4e431c6-4be8-44d7-9ff2-0d457bba7675",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "input",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.setText(
    {
      type: "Web",
      id: "294ca06e-1700-48a3-9211-7c5c8b669e67",
      attributes: {
        type: "text",
        class: "form-control",
        id: "txt-username",
        name: "username",
        placeholder: "Username",
        value: "",
        autocomplete: "off",
      },
      childIndex: 1,
      hashes: { "md5.v1": "57f176ba19cb19cc93acaba2dbde6b10" },
      name: "input - Username",
      selectors: [
        {
          id: "bfdad4d5-fe3b-4012-93d8-096c44aeab07",
          type: "CSS",
          value: "#txt-username",
          isDefault: true,
        },
        {
          id: "d4e431c6-4be8-44d7-9ff2-0d457bba7675",
          type: "Attribute",
          value: null,
          isDefault: true,
        },
      ],
      selectorType: "CSS",
      tag: "input",
      text: "",
      pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
      parentIframe: null,
      shadowRoot: null,
    },
    "John Doe"
  );
  await web.click({
    type: "Web",
    id: "a51c2655-31dc-474b-b01c-f8aa33e4efe6",
    attributes: { class: "input-group" },
    childIndex: 1,
    hashes: { "md5.v1": "a66ae4d3f9aae90c91376407907f4a15" },
    name: "div - input-group",
    selectors: [
      {
        id: "4300fafc-f41c-49da-9dd7-48a57d021e0b",
        type: "CSS",
        value: ".form-group:nth-child(2) .input-group",
        isDefault: true,
      },
      {
        id: "bf5a9a53-eb5b-435b-9f7d-56ea024013f0",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "div",
    text: "\t",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "e0c6944d-fe68-4199-a8cf-f8d50f1867a8",
    attributes: {
      class: "form-horizontal",
      action: "https://katalon-demo-cura.herokuapp.com/authenticate.php",
      method: "post",
    },
    childIndex: 1,
    hashes: { "md5.v1": "8ce522d403879fdd769a7addd1fed33c" },
    name: "form - Demo account",
    selectors: [
      {
        id: "42c18d4b-c96f-4417-83bb-6e8602a69c69",
        type: "CSS",
        value: ".form-horizontal",
        isDefault: true,
      },
      {
        id: "d7f9a9d9-8392-475e-a188-c6e8fe8a0dd8",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "form",
    text: "Demo account\n\t\n\t\nUsername\nPassword\nLogin",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "032e044f-5cd8-4327-8a78-d451cb1f9d3f",
    attributes: {
      type: "password",
      class: "form-control",
      id: "txt-password",
      name: "password",
      placeholder: "Password",
      value: "",
      autocomplete: "off",
    },
    childIndex: 1,
    hashes: { "md5.v1": "fe634c654141065106a978262a410740" },
    name: "input - Password",
    selectors: [
      {
        id: "e0be0923-d88e-4dbf-99d2-377303897fd2",
        type: "CSS",
        value: "#txt-password",
        isDefault: true,
      },
      {
        id: "5bd46659-2cb0-4c87-9c11-c91a47ff4f39",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "input",
    text: "",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.setEncryptedText(
    {
      type: "Web",
      id: "032e044f-5cd8-4327-8a78-d451cb1f9d3f",
      attributes: {
        type: "password",
        class: "form-control",
        id: "txt-password",
        name: "password",
        placeholder: "Password",
        value: "",
        autocomplete: "off",
      },
      childIndex: 1,
      hashes: { "md5.v1": "fe634c654141065106a978262a410740" },
      name: "input - Password",
      selectors: [
        {
          id: "e0be0923-d88e-4dbf-99d2-377303897fd2",
          type: "CSS",
          value: "#txt-password",
          isDefault: true,
        },
        {
          id: "5bd46659-2cb0-4c87-9c11-c91a47ff4f39",
          type: "Attribute",
          value: null,
          isDefault: true,
        },
      ],
      selectorType: "CSS",
      tag: "input",
      text: "",
      pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
      parentIframe: null,
      shadowRoot: null,
    },
    "1aec46562384bc9199c55381cf9d1073-U2FsdGVkX1/MRY4F9BKQs5p71yTKM+/3jG4StPnE7eu7aQ6yxD6BfaMfDTsFPYMQ"
  );
  await web.click({
    type: "Web",
    id: "78e67ed2-73a9-4734-830c-b56675c83ae1",
    attributes: { id: "login", class: "section" },
    childIndex: 5,
    hashes: { "md5.v1": "39767aafe2f3f9daf73590c54cb578ef" },
    name: "section - Login",
    selectors: [
      {
        id: "6f4daf87-0ffa-471b-956f-5e755f86c1c0",
        type: "CSS",
        value: "#login",
        isDefault: true,
      },
      {
        id: "d0e7d0ef-29c0-4456-b9c6-25e48d106517",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "section",
    text: "Login\n\nPlease login to make appointment.\n\nDemo account\n\t\n\t\nUsername\nPassword\nLogin",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "90410287-ce26-4dc9-8b0d-42ad44e3bb7b",
    attributes: { id: "btn-login", type: "submit", class: "btn btn-default" },
    childIndex: 1,
    hashes: { "md5.v1": "50aa64147a00037c420def1e18673ac9" },
    name: "button - Login",
    selectors: [
      {
        id: "18551063-fc04-477d-81a8-3024b590869b",
        type: "CSS",
        value: "#btn-login",
        isDefault: true,
      },
      {
        id: "d7d4579e-d754-469b-b31d-0fc77291411a",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "button",
    text: "Login",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/profile.php#login",
    parentIframe: null,
    shadowRoot: null,
  });
  await web.click({
    type: "Web",
    id: "45fa1f98-8076-4db8-8956-2dbe1f50c839",
    attributes: { class: "radio-inline" },
    childIndex: 2,
    hashes: { "md5.v1": "0327f13f35dc137bce039c73c4d1a0b4" },
    name: "label - Medicaid",
    selectors: [
      {
        id: "3e630900-af12-4511-8374-48affb250ebd",
        type: "CSS",
        value: ".radio-inline:nth-child(2)",
        isDefault: true,
      },
      {
        id: "9da0a84e-d4aa-44b1-8295-34fb19d01133",
        type: "Attribute",
        value: null,
        isDefault: true,
      },
    ],
    selectorType: "CSS",
    tag: "label",
    text: "Medicaid",
    pageUrl: "https://katalon-demo-cura.herokuapp.com/#appointment",
    parentIframe: null,
    shadowRoot: null,
  });
});